"""AC-01G characterization-freeze support (test-side, never production code).

The layout-v2 search behaviour at the freeze SHA is pinned so a refactor
cannot change it silently. Park's review of PR #35 established, from CI
evidence, that ONE mechanism cannot do this job on its own: the same source
tree produced different last bits of ``footprintDistance`` /
``referencePosition`` / ``cheapProxy`` on two GitHub runners (FULL backend
green, ordinary CI red, identical tree ``75b67c6``). So the freeze has TWO
layers with different portability contracts, and this module owns both:

LAYER A — the STATIC COMMITTED baseline, compared EXACTLY. It records the
DISCRETE decision outputs of the search: candidate ids and order, family,
declared parameters, status, stage, failure reasons, shortlist order and
flags, ranking, rank, winner, screen authority, clearance basis, counts, and
key presence / order. Every float leaf and every numeric list is REMOVED by
``discrete_observations`` — not rounded, removed — because an IEEE bit
pattern is not a property of the source tree across CPU / BLAS builds, while
a decision is. Two subtrees of declared LITERALS are kept verbatim, floats
included (``DECLARED_LITERAL_PATHS``): a candidate's enumeration
``parameters`` (the grid values its id encodes, rule 142) and the
``searchConfig`` echo (measured byte-equal to ``scenario.layout.model_dump``).
Strings carry no high-precision floats (measured over all four baselines).

LAYER B — the SAME-RUNNER numeric equivalence, compared EXACTLY, never
committed. The full float-bearing ``observations`` of the freeze-SHA
production source (``git archive <sha> backend/src``) and of HEAD are
generated by ONE script (``scripts/characterization_observe.py``) from ONE
interpreter on ONE machine, and must be bit-identical. That answers the
question the refactor actually raises — "is HEAD the same function as the
base ON THIS PLATFORM?" — without asking every CPU on earth to agree on a
last bit. There is NO tolerance and NO rounding anywhere in this module
(``test_layout_characterization.py`` pins that statically).

Also owned here: the wall-clock mask — the SAME rule
``tests/test_layout_policy_restore.py`` established (drop ``sourceRevision``
and every key ending in ``Seconds``), asserted identical so it cannot widen
by drift — and the baseline self-fingerprint (rule 181's "never auto-
rewritten": the generating git SHA is pinned as a CONSTANT here, so a
regeneration needs a reviewed source edit).

Authority: a characterization baseline records what the code DID at the
freeze SHA. It is not an engineering specification and proves no constraint
correct; a difference is a signal to explain, never on its own a defect.
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "characterization"

#: 2 = LAYER A discrete baseline (AC-01G review correction 2). Version 1 was
#: the float-bearing full observation set; it is not readable any more.
CHARACTERIZATION_SCHEMA_VERSION = 2

#: the git SHA the committed baselines were generated at (AC-01G freeze) —
#: ALSO the base side of the LAYER B same-runner comparison
BASELINE_GIT_SHA = "3951d98d91235facb6b95e9d646f0dc62b7c9835"

#: the frozen cases (minegen.regression.layout_v2.FULL_SUITE keys)
CASE_KEYS: tuple[str, ...] = (
    "TABULAR-REFERENCE",
    "WARPED_VEIN-301",
    "ACCESS-INFEASIBLE",
    "GEOMETRY-STRESS",
)

#: wall-clock keys — identical to tests/test_layout_policy_restore.py
WALL_CLOCK_KEYS = {"sourceRevision"}


def strip_wall_clock(obj: Any) -> Any:
    """Drop wall-clock keys (``sourceRevision``, ``*Seconds``) recursively.

    Deliberately NOT a general normalisation: everything else is compared as
    it is emitted. If two clean runs differ in some other key, that is a
    finding about the code, not something to mask away.
    """
    if isinstance(obj, dict):
        return {
            k: strip_wall_clock(v)
            for k, v in obj.items()
            if k not in WALL_CLOCK_KEYS and not str(k).endswith("Seconds")
        }
    if isinstance(obj, list):
        return [strip_wall_clock(v) for v in obj]
    return obj


def key_paths(obj: Any, prefix: str = "") -> list[str]:
    """Ordered key paths of a payload.

    Descends into every dict (recording each key in emission order) and into
    list elements that are themselves containers. A list of scalars is a
    LEAF path: ``candidates[3].centerline.points`` is one entry, not 40 000.
    Computed on the UNMASKED payload, so a masked key still shows up as a
    path — a key added, removed or reordered fails even though its value
    was masked.
    """
    out: list[str] = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            p = f"{prefix}.{k}" if prefix else str(k)
            out.append(p)
            out.extend(key_paths(v, p))
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            if isinstance(v, dict | list):
                out.extend(key_paths(v, f"{prefix}[{i}]"))
    return out


def payload_sha(payload: dict[str, Any]) -> str:
    """C6: sha256 of the wall-clock-stripped payload in EMISSION key order.

    LAYER B only — it hashes every float, so it is portable only within one
    platform, which is exactly the contract of that layer.
    """
    text = json.dumps(strip_wall_clock(payload), sort_keys=False, separators=(",", ":"))
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


# --------------------------------------------------------------------------- #
# C1 – C6 projections (one definition, shared by the generator and the test)
# --------------------------------------------------------------------------- #

#: per-candidate keys frozen after the cheap stage. For a SHORTLISTED
#: candidate ``status`` / ``stageReached`` are its POST-DETAILED values: the
#: search publishes ONE result object and exposes no mid-run snapshot, and
#: reaching into the stage methods would freeze private internals instead of
#: behaviour. Recorded as-is and stated, never silently implied.
_C2_KEYS = (
    "status",
    "stageReached",
    "failureReasons",
    "cheapProxy",
    "screenedLevels",
    "requiredLevels",
    "accessibleLevels",
    "rampLevelReferences",
    "accessScreen",
)

#: per-candidate keys frozen after the detailed stage
_C4_KEYS = (
    "status",
    "stageReached",
    "failureReasons",
    "failureDetail",
    "clearance",
    "validation",
    "scores",
    "exposure",
    "diagnostics",
    "derived",
    "access",
)

#: bulk geometry dropped from the READABLE C4 projection — it stays covered
#: exactly by the LAYER B payload sha, which hashes the whole payload
_ACCESS_BULK = ("centerline", "pieces")


def c1_enumeration(payload: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        {
            "candidateId": c["candidateId"],
            "family": c["family"],
            "parameters": c["parameters"],
        }
        for c in payload["candidates"]
    ]


def c2_post_cheap(payload: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        {"candidateId": c["candidateId"], **{k: c[k] for k in _C2_KEYS}}
        for c in payload["candidates"]
    ]


def c3_shortlist(payload: dict[str, Any]) -> dict[str, Any]:
    return {
        "shortlist": list(payload["shortlist"]),
        "shortlisted": [[c["candidateId"], c["shortlisted"]] for c in payload["candidates"]],
    }


def c4_detailed(payload: dict[str, Any]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for c in payload["candidates"]:
        if not c["shortlisted"]:
            continue
        rec: dict[str, Any] = {"candidateId": c["candidateId"], **{k: c[k] for k in _C4_KEYS}}
        accesses = c.get("levelAccesses")
        rec["levelAccesses"] = (
            None
            if accesses is None
            else [{k: v for k, v in a.items() if k not in _ACCESS_BULK} for a in accesses]
        )
        out.append(rec)
    return out


def c5_ranking(payload: dict[str, Any]) -> dict[str, Any]:
    return {
        "ranking": list(payload["ranking"]),
        "ranks": [[c["candidateId"], c["rank"]] for c in payload["candidates"]],
        "winnerId": payload["winnerId"],
    }


#: list indices collapsed so the 92 sibling candidate rows contribute ONE
#: shape entry instead of 92 identical ones.
_INDEX = re.compile(r"\[\d+\]")


def key_path_shape(paths: list[str]) -> list[str]:
    """The order-preserving DISTINCT key paths with list indices collapsed.

    ``candidates[0].scores.total`` and ``candidates[91].scores.total`` are one
    shape entry ``candidates[].scores.total``. A key ADDED to a single row
    still creates a new shape entry, so the schema net is unchanged while the
    committed baseline drops from 39 577 strings to 483 (TABULAR, measured).
    Multiplicity and per-row order are not lost: ``keyPathCount`` pins the
    total and ``keyPathsSha256`` pins the full ORDERED list.
    """
    out: list[str] = []
    seen: set[str] = set()
    for p in paths:
        shape = _INDEX.sub("[]", p)
        if shape not in seen:
            seen.add(shape)
            out.append(shape)
    return out


def c6_payload(payload: dict[str, Any]) -> dict[str, Any]:
    paths = key_paths(payload)
    joined = "\n".join(paths)
    return {
        "sha256": payload_sha(payload),
        "keyPathCount": len(paths),
        "keyPathsSha256": hashlib.sha256(joined.encode("utf-8")).hexdigest(),
        "keyPathShape": key_path_shape(paths),
    }


def observations(payload: dict[str, Any]) -> dict[str, Any]:
    """LAYER B: the whole C1–C6 observation set of one search result, floats
    included, wall clock masked and nothing else. Compared exactly, same
    runner, base vs HEAD."""
    return {
        "header": {
            "status": payload["status"],
            "layoutVersion": payload["layoutVersion"],
            "clearanceBasis": payload["clearanceBasis"],
            "candidateCount": payload["candidateCount"],
            "feasibleCount": payload["feasibleCount"],
            "serviceableLevelCount": payload["serviceableLevelCount"],
            "requiredLevels": payload["requiredLevels"],
            "portal": payload["portal"],
            "portalGenerated": payload["portalGenerated"],
            "clearanceErrorBound": payload["clearanceErrorBound"],
            "requiredClearance": payload["requiredClearance"],
            "accessReach": payload["accessReach"],
            "footwallStandoff": payload["footwallStandoff"],
            "searchConfig": payload["searchConfig"],
            "performance": strip_wall_clock(payload["performance"]),
        },
        "c1Enumeration": c1_enumeration(payload),
        "c2PostCheap": c2_post_cheap(payload),
        "c3Shortlist": c3_shortlist(payload),
        "c4Detailed": c4_detailed(payload),
        "c5Ranking": c5_ranking(payload),
        "c6Payload": c6_payload(payload),
    }


#: the observation sections a baseline carries, in COMPARISON order: C1 … C6
#: first, so a failure is reported against the stage it belongs to, and the
#: result header (portal, level set, config, masked performance) last.
SECTIONS: tuple[str, ...] = (
    "c1Enumeration",
    "c2PostCheap",
    "c3Shortlist",
    "c4Detailed",
    "c5Ranking",
    "c6Payload",
    "header",
)


# --------------------------------------------------------------------------- #
# LAYER A — the discrete projection
# --------------------------------------------------------------------------- #

#: observation subtrees kept VERBATIM in LAYER A although they contain floats,
#: because those floats are declared literals, not computed quantities:
#:
#: * ``c1Enumeration[].parameters`` — the enumeration-grid values a candidate
#:   id encodes (rule 142: ``SPIRAL-n1-CW-e-45-g0.120`` IS its parameters);
#: * ``header.searchConfig`` — the ``scenario.layout`` echo, measured
#:   byte-equal to ``scenario.layout.model_dump(mode="json", by_alias=True)``
#:   on TABULAR-REFERENCE (and pinned by a test).
#:
#: A path is (section, key) with the section's list rows implied. Nothing
#: else is exempt: a new float-bearing "declared" field must be added HERE,
#: in a reviewed change, with its literal-ness stated.
DECLARED_LITERAL_PATHS: tuple[tuple[str, str], ...] = (
    ("c1Enumeration", "parameters"),
    ("header", "searchConfig"),
)

#: LAYER B-only entries of ``c6Payload``: a hash over every float
_C6_NUMERIC_KEYS = ("sha256",)


def _is_numeric_list(value: Any) -> bool:
    """A non-empty list whose every element is a float or a numeric list —
    geometry (``[x, y, z]``, point lists) and float vectors. An empty list is
    DISCRETE information (``failureReasons: []``) and is kept."""
    if not isinstance(value, list) or not value:
        return False
    return all(
        (isinstance(v, float) and not isinstance(v, bool)) or _is_numeric_list(v) for v in value
    )


def discrete_projection(obj: Any) -> Any:
    """Remove every float leaf and every numeric list, recursively; keep
    ints, bools, strings, ``None``, dicts and discrete lists (with their
    order). Removal, never rounding: a removed value is simply not part of
    the LAYER A contract."""
    if isinstance(obj, dict):
        out: dict[Any, Any] = {}
        for k, v in obj.items():
            if isinstance(v, float) and not isinstance(v, bool):
                continue
            if _is_numeric_list(v):
                continue
            out[k] = discrete_projection(v)
        return out
    if isinstance(obj, list):
        return [
            discrete_projection(v)
            for v in obj
            if not (isinstance(v, float) and not isinstance(v, bool)) and not _is_numeric_list(v)
        ]
    return obj


def discrete_observations(payload: dict[str, Any]) -> dict[str, Any]:
    """LAYER A: the committed, platform-portable projection of one result."""
    return discrete_from_observations(observations(payload))


def discrete_from_observations(full: dict[str, Any]) -> dict[str, Any]:
    """LAYER A from an already-built LAYER B observation set (the form the
    ``characterization_observe.py`` subprocess emits).

    ``observations`` with every float removed (``discrete_projection``), the
    declared-literal subtrees restored verbatim, and the float-hashing C6
    entry dropped. The key-path views stay: they are key NAMES, and pinning
    that a float key still EXISTS is part of the discrete contract even
    though its value is not.
    """
    out = discrete_projection(full)
    for section, key in DECLARED_LITERAL_PATHS:
        source, target = full[section], out[section]
        if isinstance(source, list):
            for src_row, dst_row in zip(source, target, strict=True):
                dst_row[key] = src_row[key]
        else:
            target[key] = source[key]
    for key in _C6_NUMERIC_KEYS:
        out["c6Payload"].pop(key, None)
    return out


def float_leaf_paths(obj: Any, prefix: str = "") -> list[str]:
    """Every path holding a float or a numeric list — the audit behind
    ``discrete_observations`` (a test asserts it is empty outside the
    declared-literal subtrees)."""
    out: list[str] = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            p = f"{prefix}.{k}" if prefix else str(k)
            if (isinstance(v, float) and not isinstance(v, bool)) or _is_numeric_list(v):
                out.append(p)
            else:
                out.extend(float_leaf_paths(v, p))
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            p = f"{prefix}[{i}]"
            if (isinstance(v, float) and not isinstance(v, bool)) or _is_numeric_list(v):
                out.append(p)
            else:
                out.extend(float_leaf_paths(v, p))
    return out


# --------------------------------------------------------------------------- #
# self-fingerprint (rule 181 applied to a characterization baseline)
# --------------------------------------------------------------------------- #


def content_fingerprint(git_sha: str, body: dict[str, Any]) -> str:
    """sha256 over the generating git SHA and the baseline BODY.

    The body is hashed exactly as written: a characterization freeze compares
    bits of its discrete record, not tolerances.
    """
    canon = json.dumps(body, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(f"{git_sha}\n{canon}".encode()).hexdigest()


def baseline_path(case_key: str) -> Path:
    return FIXTURE_DIR / f"{case_key.replace('-', '_').lower()}.json"


def load_baseline(case_key: str) -> dict[str, Any]:
    """Load a committed baseline and VERIFY its self-fingerprint.

    Loud, explicit failure on a hand-edited or partially-regenerated file;
    never repaired, never rewritten.
    """
    path = baseline_path(case_key)
    if not path.exists():
        raise AssertionError(
            f"MISSING CHARACTERIZATION BASELINE for {case_key}: {path} does not exist. "
            "The AC-01G freeze baseline is generated ONCE, at the freeze SHA "
            f"{BASELINE_GIT_SHA}, by scripts/generate_characterization_baseline.py. "
            "Do not regenerate it to make this test pass."
        )
    data: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
    meta = data.get("metadata")
    if not isinstance(meta, dict):
        raise AssertionError(f"CORRUPT CHARACTERIZATION BASELINE {path}: no metadata object")
    if meta.get("schemaVersion") != CHARACTERIZATION_SCHEMA_VERSION:
        raise AssertionError(
            f"CHARACTERIZATION BASELINE {case_key}: schemaVersion "
            f"{meta.get('schemaVersion')!r} != {CHARACTERIZATION_SCHEMA_VERSION}"
        )
    if meta.get("caseKey") != case_key:
        raise AssertionError(
            f"CHARACTERIZATION BASELINE {path}: caseKey {meta.get('caseKey')!r} != {case_key!r}"
        )
    body = {k: v for k, v in data.items() if k != "metadata"}
    recorded = meta.get("contentFingerprint")
    actual = content_fingerprint(str(meta.get("generatedFromGitSha")), body)
    if recorded != actual:
        raise AssertionError(
            f"TAMPERED CHARACTERIZATION BASELINE {path}: recorded contentFingerprint "
            f"{str(recorded)[:12]}… does not match its own content ({actual[:12]}…) under the "
            f"recorded git SHA {meta.get('generatedFromGitSha')!r}. The baseline body or the "
            "recorded SHA was edited by hand, or the file was written by something other than "
            "scripts/generate_characterization_baseline.py. It is NEVER auto-rewritten: restore "
            "the committed file, or regenerate deliberately and update BASELINE_GIT_SHA in "
            "tests/characterization_support.py in the same reviewed change."
        )
    return data
