"""Phase 23B adapter API (directive §52–§58, §68): the four export routes,
typed refusals, read-only proof and no generation — FAST on a world-only
scenario (the full chains are covered by ``test_adapters_e2e``)."""

from __future__ import annotations

import hashlib
import io
import json
import zipfile
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from minegen.exchange.models import MINE_EXCHANGE_VERSION
from minegen.services.scenario_service import ScenarioStore
from tests.test_world_api import _create

TARGETS = ("ventsim", "anylogic", "unity", "unreal")


def _state(root: Path) -> dict[str, tuple[int, int, str]]:
    return {
        str(p.relative_to(root)): (
            p.stat().st_size,
            p.stat().st_mtime_ns,
            hashlib.sha256(p.read_bytes()).hexdigest(),
        )
        for p in sorted(root.rglob("*"))
        if p.is_file()
    }


@pytest.mark.parametrize("target", TARGETS)
def test_unknown_scenario_is_404_and_world_required_is_409(client: TestClient, target: str) -> None:
    r = client.post(f"/api/v1/scenarios/nope/export/{target}")
    assert r.status_code == 404, r.text
    sid = _create(client)
    r = client.post(f"/api/v1/scenarios/{sid}/export/{target}")
    assert r.status_code == 409 and r.json()["detail"]["code"] == "WORLD_NOT_GENERATED", r.text


def test_world_only_scenario_typed_refusals_partial_packages_and_read_only(
    client: TestClient, store: ScenarioStore
) -> None:
    sid = _create(client)
    assert client.post(f"/api/v1/scenarios/{sid}/world/generate").status_code == 200
    scenario_dir = Path(store.root) / sid
    econ = scenario_dir / "economics.json"
    econ.write_bytes(b'{"note": "user authored"}')
    before = _state(scenario_dir)
    assert {"scenario.json", "arrays.npz"} <= {Path(k).name for k in before}

    r = client.post(f"/api/v1/scenarios/{sid}/export/ventsim")
    assert r.status_code == 409, r.text
    detail = r.json()["detail"]
    assert detail["code"] == "ADAPTER_REQUIRED_SOURCE_ABSENT"
    assert "adapter=VENTSIM" in detail["message"] and "group=EXCAVATIONS" in detail["message"]
    r = client.post(f"/api/v1/scenarios/{sid}/export/anylogic")
    assert r.status_code == 409, r.text
    detail = r.json()["detail"]
    assert detail["code"] == "ADAPTER_REQUIRED_SOURCE_ABSENT"
    assert "adapter=ANYLOGIC" in detail["message"] and "group=NETWORK" in detail["message"]

    packages: dict[str, bytes] = {}
    for target in ("unity", "unreal"):
        r = client.post(f"/api/v1/scenarios/{sid}/export/{target}")
        assert r.status_code == 200, r.text
        assert r.headers["content-type"] == "application/zip"
        assert r.headers["content-disposition"] == (
            f'attachment; filename="minegen_{sid}_{target}.zip"'
        )
        assert r.headers["x-adapter-name"] == target.upper()
        assert r.headers["x-adapter-version"] == "0.1.0"
        assert r.headers["x-mineexchange-version"] == MINE_EXCHANGE_VERSION
        assert r.headers["cache-control"] == "no-store"
        packages[target] = r.content
        with zipfile.ZipFile(io.BytesIO(r.content)) as zf:
            names = zf.namelist()
            root = f"{target}_package/"
            assert all(n.startswith(root) for n in names)
            m = json.loads(zf.read(f"{root}adapter_manifest.json"))
        assert m["targetApplication"] == target.upper()
        assert m["sourceScenarioId"] == sid
        assert m["sourceMineExchangeVersion"] == MINE_EXCHANGE_VERSION
        states = {s["group"]: s["state"] for s in m["sourceStates"]}
        assert states["NETWORK"] == "ARTIFACT_ABSENT" and states["EXCAVATIONS"] == "ARTIFACT_ABSENT"
        assert m["details"]["assetCount"] == 3 and m["details"]["networkIncluded"] is False

    # a second export is byte-identical
    r = client.post(f"/api/v1/scenarios/{sid}/export/unity")
    assert r.content == packages["unity"]
    # read-only: scenario.json, arrays.npz, economics.json and derived/ untouched;
    # nothing generated, nothing persisted (no zip, no derived artifact)
    assert _state(scenario_dir) == before
    assert not list(Path(store.root).rglob("*.zip"))
    # no derived artifact was generated by the exports (the world-only derived
    # set is exactly what it was before the first export)
    assert {Path(k).name for k in _state(scenario_dir) if "derived" in k} == {
        Path(k).name for k in before if "derived" in k
    }
    assert econ.read_bytes() == b'{"note": "user authored"}'
