/** Phase 22A/B test fixture: the hand-built mine of the backend tests
 * (`backend/tests/analysis_support.py`) as the API emits it. */
import type { EconomicsConfig, MineAnalysisPayload } from '@/types/analysis'

export const CONFIG: EconomicsConfig = {
  version: 1,
  currencyCode: 'USD',
  developmentCosts: {
    rampPerM: 10,
    levelAccessPerM: 8,
    driftPerM: 6,
    crosscutPerM: 5,
    raisePerM: 7,
    shaftPerM: 0,
    shaftStationAccessPerM: 0,
  },
  productionCosts: {
    longholeOpenStopingPerTonne: 2,
    cutAndFillPerTonne: 3,
    roomAndPillarPerTonne: 4,
  },
  processingCostPerTonne: 1,
  backfillCostPerM3: 0.5,
  fixedOperatingCostPerDay: 10,
  grossRevenuePerMinedTonne: 5,
  initialCapitalCost: 500,
  annualDiscountRate: 0.1,
  cashflowBucketDays: 30,
}

export const DISCLAIMER =
  'Synthetic planning economics. Not a resource/reserve estimate or feasibility study.'

const bucket = (
  index: number,
  net: number,
  cumulative: number,
  over: Partial<MineAnalysisPayload['economics']['cashflow'][number]> = {},
) => ({
  index,
  startDay: index * 30,
  endDay: (index + 1) * 30,
  developmentCost: 0,
  productionMiningCost: 0,
  processingCost: 0,
  backfillCost: 0,
  fixedOperatingCost: 300,
  initialCapitalCost: 0,
  revenue: 0,
  netCashflow: net,
  cumulativeCashflow: cumulative,
  discountedNetCashflow: net,
  ...over,
})

export const FULL: MineAnalysisPayload = {
  status: 'SUCCESS',
  sources: {
    scenarioRevision: 's',
    networkRevision: 'n',
    productionRevision: 'p',
    timelineRevision: 't',
    economicsRevision: 'e',
  },
  development: {
    availability: 'AVAILABLE',
    reason: null,
    categories: [
      { edgeType: 'RAMP', edgeCount: 2, totalLengthM: 150, grossExcavationVolumeM3: 3000 },
      { edgeType: 'LEVEL_ACCESS', edgeCount: 1, totalLengthM: 30, grossExcavationVolumeM3: 600 },
      { edgeType: 'DRIFT', edgeCount: 1, totalLengthM: 40, grossExcavationVolumeM3: 640 },
      { edgeType: 'CROSSCUT', edgeCount: 1, totalLengthM: 10, grossExcavationVolumeM3: 160 },
      { edgeType: 'RAISE', edgeCount: 0, totalLengthM: 0, grossExcavationVolumeM3: 0 },
      { edgeType: 'SHAFT', edgeCount: 0, totalLengthM: 0, grossExcavationVolumeM3: 0 },
      {
        edgeType: 'SHAFT_STATION_ACCESS',
        edgeCount: 0,
        totalLengthM: 0,
        grossExcavationVolumeM3: 0,
      },
    ],
    totals: {
      totalDevelopmentLengthM: 230,
      grossDevelopmentVolumeM3: 4400,
      rampLengthM: 150,
      levelAccessLengthM: 30,
      driftLengthM: 40,
      crosscutLengthM: 10,
      shaftLengthM: 0,
      shaftStationAccessLengthM: 0,
    },
    crossCheck: { toleranceM: 1e-6, maxLengthDifferenceM: 0, maxCountDifference: 0 },
  },
  production: {
    availability: 'AVAILABLE',
    reason: null,
    method: 'LONGHOLE_OPEN_STOPING',
    productionObjectCount: 2,
    totalProductionVolumeM3: 1600,
    totalPlannedMinedTonnes: 4000,
    weightedMeanGradeProxy: 2.5,
    detail: { kind: 'LONGHOLE_OPEN_STOPING', stopeCount: 2, levelIntervalCount: 1 },
  },
  schedule: {
    availability: 'AVAILABLE',
    reason: null,
    taskCount: 15,
    developmentTaskCount: 5,
    productionTaskCount: 10,
    startDay: 0,
    endDay: 120,
    mineDurationDays: 120,
    rampCompletionDay: 30,
    firstProductionDay: 50,
  },
  ratios: {
    availability: 'AVAILABLE',
    reason: null,
    developmentMetresPerKt: 57.5,
    grossDevelopmentM3PerKt: 1100,
  },
  economics: {
    availability: 'AVAILABLE',
    reason: null,
    economicsRevision: 'e',
    currencyCode: 'USD',
    cashflowBucketDays: 30,
    annualDiscountRate: 0.1,
    revenueModel: 'GROSS_REVENUE_PER_MINED_TONNE',
    npvConvention: 'MID_BUCKET_MIDPOINT',
    summary: {
      developmentCost: 2030,
      productionMiningCost: 8000,
      processingCost: 4000,
      backfillCost: 0,
      fixedOperatingCost: 1200,
      initialCapitalCost: 500,
      totalCost: 15730,
      totalRevenue: 20000,
      undiscountedNetCashflow: 4270,
      npv: 4038.51,
    },
    cashflow: [
      bucket(0, -2540, -2540, { developmentCost: 1740, initialCapitalCost: 500 }),
      bucket(1, -2590, -5130, { developmentCost: 290, productionMiningCost: 2000 }),
      bucket(2, -2300, -7430, { productionMiningCost: 6000, processingCost: 1000, revenue: 5000 }),
      bucket(3, 11700, 4270, { processingCost: 3000, revenue: 15000 }),
    ],
    disclaimer: DISCLAIMER,
  },
}

/** a fresh scenario: nothing generated, nothing configured */
export const EMPTY: MineAnalysisPayload = {
  status: 'SUCCESS',
  sources: {
    scenarioRevision: 's',
    networkRevision: null,
    productionRevision: null,
    timelineRevision: null,
    economicsRevision: null,
  },
  development: {
    availability: 'NOT_AVAILABLE',
    reason: 'network.json not generated',
    categories: [],
    totals: null,
    crossCheck: null,
  },
  production: {
    availability: 'NOT_AVAILABLE',
    reason: 'stopes.json not generated',
    method: null,
    productionObjectCount: null,
    totalProductionVolumeM3: null,
    totalPlannedMinedTonnes: null,
    weightedMeanGradeProxy: null,
    detail: null,
  },
  schedule: {
    availability: 'NOT_AVAILABLE',
    reason: 'timeline.json not generated',
    taskCount: null,
    developmentTaskCount: null,
    productionTaskCount: null,
    startDay: null,
    endDay: null,
    mineDurationDays: null,
    rampCompletionDay: null,
    firstProductionDay: null,
  },
  ratios: {
    availability: 'NOT_AVAILABLE',
    reason: 'requires development and production',
    developmentMetresPerKt: null,
    grossDevelopmentM3PerKt: null,
  },
  economics: {
    availability: 'NOT_CONFIGURED',
    reason: 'Planning economics is not configured.',
    economicsRevision: null,
    currencyCode: null,
    cashflowBucketDays: null,
    annualDiscountRate: null,
    revenueModel: 'GROSS_REVENUE_PER_MINED_TONNE',
    npvConvention: 'MID_BUCKET_MIDPOINT',
    summary: null,
    cashflow: [],
    disclaimer: DISCLAIMER,
  },
}
