/**
 * §25 HARD GATE: the GLB primitive/group mapping proof. The fixture GLB is
 * generated by the REAL Phase 06 backend writer (two straight decline
 * segments -> SEG:A, SEG:B, PORTAL_CAP, TERMINAL_CAP) so these tests pin
 * the writer contract as GLTFLoader actually exposes it.
 */
import { readFileSync } from 'node:fs'
import { GLTFLoader, type GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'
import { Mesh } from 'three'
import { beforeAll, describe, expect, it } from 'vitest'
import {
  buildColliderUnits,
  extractTunnelRuntimeGeometry,
  PORTAL_CAP_COLLIDER_ID,
  segmentColliderId,
  TERMINAL_CAP_COLLIDER_ID,
  TunnelGeometryError,
  toThreePositions,
} from './tunnelRuntimeGeometry'

function loadFixture(): Promise<GLTF> {
  const buf = readFileSync(new URL('./__fixtures__/tunnel_two_segments.glb', import.meta.url))
  const array = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength)
  return new Promise((resolve, reject) => {
    new GLTFLoader().parse(array, '', resolve, reject)
  })
}

let gltf: GLTF

beforeAll(async () => {
  gltf = await loadFixture()
})

describe('GLTFLoader representation of the Phase 06 GLB (§7)', () => {
  it('exposes one Mesh child per primitive in primitive order, with extras on geometry.userData', () => {
    const meshes: Mesh[] = []
    gltf.scene.traverse((o) => {
      if (o instanceof Mesh) meshes.push(o as Mesh)
    })
    expect(meshes).toHaveLength(4)
    expect(meshes.map((m) => (m.geometry.userData as { role?: string }).role)).toEqual([
      'SEGMENT',
      'SEGMENT',
      'PORTAL_CAP',
      'TERMINAL_CAP',
    ])
    expect(
      meshes.map((m) => (m.geometry.userData as { segmentId?: string }).segmentId).slice(0, 2),
    ).toEqual(['SEG:A', 'SEG:B'])
    // the assumption the spec warned about: primitive extras do NOT land on
    // mesh.userData — the adapter must (and does) read geometry.userData
    expect(meshes.every((m) => Object.keys(m.userData).length === 0)).toBe(true)
  })
})

describe('tunnel runtime-geometry adapter (§25 hard gate)', () => {
  it('maps every primitive deterministically: segments in order, caps identified, nothing dropped or doubled', () => {
    const a = extractTunnelRuntimeGeometry(gltf.scene)
    const b = extractTunnelRuntimeGeometry(gltf.scene)
    expect(a.segments.map((s) => s.segmentId)).toEqual(['SEG:A', 'SEG:B'])
    expect(b.segments.map((s) => s.segmentId)).toEqual(['SEG:A', 'SEG:B'])
    expect(a.primitiveCount).toBe(4) // 2 segments + 2 caps, none dropped
    expect(a.portalCap.indices.length).toBeGreaterThan(0)
    expect(a.terminalCap.indices.length).toBeGreaterThan(0)
    const total =
      a.segments.reduce((n, s) => n + s.indices.length, 0) +
      a.portalCap.indices.length +
      a.terminalCap.indices.length
    const sourceTotal = (() => {
      let n = 0
      gltf.scene.traverse((o) => {
        if (o instanceof Mesh) n += (o as Mesh).geometry.getIndex()!.array.length
      })
      return n
    })()
    expect(total).toBe(sourceTotal) // no primitive counted twice / dropped
  })

  it('reuses the source index arrays exactly and creates no new topology', () => {
    const runtime = extractTunnelRuntimeGeometry(gltf.scene)
    const meshes: Mesh[] = []
    gltf.scene.traverse((o) => {
      if (o instanceof Mesh) meshes.push(o as Mesh)
    })
    expect(Object.is(runtime.segments[0]!.indices, meshes[0]!.geometry.getIndex()!.array)).toBe(
      true,
    )
    expect(Object.is(runtime.segments[1]!.indices, meshes[1]!.geometry.getIndex()!.array)).toBe(
      true,
    )
    expect(Object.is(runtime.portalCap.indices, meshes[2]!.geometry.getIndex()!.array)).toBe(true)
    // all primitives share the single writer POSITION accessor
    expect(Object.is(runtime.segments[0]!.positions, runtime.portalCap.positions)).toBe(true)
  })

  it('collider units carry stable Phase 15-ready ids over the canonical rotation only', () => {
    const runtime = extractTunnelRuntimeGeometry(gltf.scene)
    const units = buildColliderUnits(runtime)
    expect(units.map((u) => u.id)).toEqual([
      segmentColliderId('SEG:A'),
      segmentColliderId('SEG:B'),
      PORTAL_CAP_COLLIDER_ID,
      TERMINAL_CAP_COLLIDER_ID,
    ])
    expect(new Set(units.map((u) => u.id)).size).toBe(4)
    // one segment == one collider unit; caps separately identifiable
    expect(units.filter((u) => u.segmentId !== null)).toHaveLength(2)
    // vertices are the backend vertices under (x,y,z) -> (x,z,-y) ONLY
    const src = runtime.segments[0]!.positions
    const v = units[0]!.vertices
    expect(v.length).toBe(src.length)
    for (const i of [0, 3, 300, src.length - 3]) {
      expect(v[i]).toBe(src[i])
      expect(v[i + 1]).toBe(src[i + 2])
      expect(v[i + 2]).toBe(-src[i + 1]!)
    }
    // the shared transformed buffer is computed once, not per unit
    expect(units.every((u) => Object.is(u.vertices, units[0]!.vertices))).toBe(true)
    // indices are the source instances, untouched
    expect(Object.is(units[0]!.indices, runtime.segments[0]!.indices)).toBe(true)
  })

  it('round-trips a vertex through the pure rotation', () => {
    const out = toThreePositions(new Float32Array([1, 2, 3]))
    expect([...out]).toEqual([1, 3, -2])
  })

  it('rejects contract violations instead of guessing', () => {
    const clone = gltf.scene.clone(true)
    const meshes: Mesh[] = []
    clone.traverse((o) => {
      if (o instanceof Mesh) meshes.push(o as Mesh)
    })
    // unknown role
    const g0 = meshes[0]!.geometry.clone()
    g0.userData = { role: 'MYSTERY' }
    meshes[0]!.geometry = g0
    expect(() => extractTunnelRuntimeGeometry(clone)).toThrow(TunnelGeometryError)
    // missing cap
    const clone2 = gltf.scene.clone(true)
    const meshes2: Mesh[] = []
    clone2.traverse((o) => {
      if (o instanceof Mesh) meshes2.push(o as Mesh)
    })
    meshes2[2]!.removeFromParent()
    expect(() => extractTunnelRuntimeGeometry(clone2)).toThrow(/PORTAL_CAP/)
  })
})
